version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: REPLACE_WITH_TASK_DEFINITION_ARN
        LoadBalancerInfo:
          ContainerName: tour-catalog
          ContainerPort: 3001
        PlatformVersion: REPLACE_WITH_PLATFORM_VERSION